
[[article]]
slug = "1"
file = "hello.md"
title = "First article"
author = ""
cover = ""
pub_date = "2022-04-23"
publish = true
featured = true


[[article]]
slug = "2"
file = "zzf.md"
title = "Second article"
author = ""
cover = ""
pub_date = "2022-04-23"
publish = true
featured = true